server:
  port: 8880
spring:
  application:
    name: eureka1
eureka:
  server:
    enable-self-preservation: false
    # 此处不开启缓存
#    use-read-only-response-cache: true
    # 指定 Eviction Task 定时任务的调度频率，用于剔除过期的实例，此处未使用默认频率，频率为：5/秒，默认为：60/秒
    # 有效防止的问题是：应用实例异常挂掉，没能在挂掉之前告知Eureka server要下线掉该服务实例信息。这个就需要依赖Eureka server的EvictionTask去剔除。
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: localhost
    prefer-ip-address: true
    # 每间隔5s，向服务端发送一次心跳，证明自己依然”存活“
#    lease-renewal-interval-in-seconds: 5
#    # 告诉服务端，如果我10s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
#    lease-expiration-duration-in-seconds: 11
  client:
    # 开启健康检查
    healthcheck:
      enabled: false
    # 取服务注册信息时间间隔
    registry-fetch-interval-seconds: 5
#    #从Eureka服务端获取注册信息的时间间隔
#    registryFetchIntervalSeconds: 1
#    #更新实例信息变化到Eureka服务端的间隔时间
#    instanceInfoReplicationIntervalSeconds: 1
    #是否注册到Eureka中
    registerWithEureka: false
    #是否需要去检索寻找服务，默认是true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8880/eureka/
