spring:
  application:
    name: gateway
server:
  port: 8920

zuul:
  routes:
    cloud-base-service:
      path: /s1/**
      serviceId: product

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8880/eureka/,http://${eureka.instance.hostname}:8881/eureka/